# Generated by Django 4.1.1 on 2022-11-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default='testing2@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
