# Generated by Django 4.1.1 on 2022-11-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile_id',
            new_name='shop_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
