# Generated by Django 4.1.1 on 2022-11-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shop',
            name='unique_shop_key',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='LowKey.shop'),
        ),
    ]
