# Generated by Django 4.1.1 on 2022-11-02 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000240B58911B0>', on_delete=django.db.models.deletion.CASCADE, related_name='shop_name', to='LowKey.profile', to_field='name'),
        ),
    ]
