# Generated by Django 4.1.1 on 2022-11-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0002_rename_profile_id_product_shop_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_key',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop_id', 'product_id'), name='unique_product_key'),
        ),
    ]
