# Generated by Django 4.1.1 on 2022-10-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0002_profile_shop_product_product_unique_product_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LowKey.shop'),
        ),
    ]
