# Generated by Django 4.1.1 on 2022-11-27 05:11

import LowKey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0003_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=LowKey.models.product_upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=LowKey.models.shop_upload_to, verbose_name='Image'),
        ),
    ]
