# Generated by Django 4.1.1 on 2022-11-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0002_shop_rating_alter_product_rating_and_more'),
        ('LowKey', '0003_product_user'),
    ]

    operations = [
    ]
