# Generated by Django 4.1.1 on 2022-11-27 02:42

import LowKey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to=LowKey.models.shop_upload_to, verbose_name='Image'),
        ),
    ]
