# Generated by Django 4.1.1 on 2022-12-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0004_product_image_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(default="Ketan's Old Emporium", on_delete=django.db.models.deletion.CASCADE, to='LowKey.shop', to_field='name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
