# Generated by Django 4.1.1 on 2022-12-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0005_product_shop_name_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LowKey.shop', to_field='name'),
        ),
    ]
