# Generated by Django 4.1.1 on 2022-10-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0005_remove_product_unique_product_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002612CB44790>', on_delete=django.db.models.deletion.CASCADE, related_name='shop_name', to='LowKey.profile', to_field='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
