# Generated by Django 4.1.1 on 2022-12-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowKey', '0006_alter_product_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_name',
            field=models.TextField(null=True),
        ),
    ]
